INSERT INTO Students VALUES (2, Cayla Dion, Sophomore, 2.0);
INSERT INTO Students VALUES (3, Gayla Inez, Freshman, 3.4);
INSERT INTO Students VALUES (4, Cathi Shae, Senior, 3.0);
INSERT INTO Students VALUES (5, Sonja Benita, Sophomore, 2.6);
INSERT INTO Students VALUES (6, Bobbette Viola, Senior, 0.3);
INSERT INTO Students VALUES (7, Vitia Tootsie, Senior, 3.8);
INSERT INTO Students VALUES (8, Tansy Judy, Freshman, 0.7);
INSERT INTO Students VALUES (9, Oralle Johanna, Junior, 3.4);
INSERT INTO Students VALUES (10, Kellia Martita, Freshman, 3.2);
INSERT INTO Students VALUES (11, Vida Cherrita, Freshman, 0.9);
INSERT INTO Students VALUES (12, Emmalynn Wylma, Junior, 1.9);
INSERT INTO Students VALUES (13, Joycelin Babita, Freshman, 3.5);
INSERT INTO Students VALUES (14, Amelina Krystyna, Freshman, 0.9);
INSERT INTO Students VALUES (15, Danice Mehetabel, Junior, 2.8);
INSERT INTO Students VALUES (16, Joella Anett, Sophomore, 3.5);
INSERT INTO Students VALUES (17, Chelsey Druci, Junior, 0.9);
INSERT INTO Students VALUES (18, Adina Marleah, Sophomore, 3.7);
INSERT INTO Students VALUES (19, Andriana Leslie, Senior, 1.4);
INSERT INTO Students VALUES (20, Gertrudis Phebe, Freshman, 1.4);
INSERT INTO Students VALUES (21, Malissa Elwira, Sophomore, 3.9);
INSERT INTO Students VALUES (22, Reina Filia, Senior, 4.0);
INSERT INTO Students VALUES (23, Jayne Carine, Junior, 3.9);
INSERT INTO Students VALUES (24, Emmye Wileen, Senior, 3.4);
INSERT INTO StudentLogin VALUES (0, aannadianna, JZ2)bkNZ);
INSERT INTO StudentLogin VALUES (1, equintina, rwSS5#Vy);
INSERT INTO StudentLogin VALUES (2, cdion, 9up5W9^S);
INSERT INTO StudentLogin VALUES (3, ginez, dVcbRJYx);
INSERT INTO StudentLogin VALUES (4, cshae, vFCCGpsb);
INSERT INTO StudentLogin VALUES (5, sbenita, VjQdhjob);
INSERT INTO StudentLogin VALUES (6, bviola, eGpmMXsg);
INSERT INTO StudentLogin VALUES (7, vtootsie, REuoxgAK);
INSERT INTO StudentLogin VALUES (8, tjudy, faEPPGDs);
INSERT INTO StudentLogin VALUES (9, ojohanna, qJKYZXXu);
INSERT INTO StudentLogin VALUES (10, kmartita, bumPaitr);
INSERT INTO StudentLogin VALUES (11, vcherrita, eakbRyKw);
INSERT INTO StudentLogin VALUES (12, ewylma, LMihKTCe);
INSERT INTO StudentLogin VALUES (13, jbabita, tLngDSWF);
INSERT INTO StudentLogin VALUES (14, akrystyna, oVhmcNbB);
INSERT INTO StudentLogin VALUES (15, dmehetabel, mwnpoMJE);
INSERT INTO StudentLogin VALUES (16, janett, xwwxkLyM);
INSERT INTO StudentLogin VALUES (17, cdruci, mBHhuRey);
INSERT INTO StudentLogin VALUES (18, amarleah, emsUDsDw);
INSERT INTO StudentLogin VALUES (19, aleslie, tScQEuEa);
INSERT INTO StudentLogin VALUES (20, gphebe, EQDUPUhP);
INSERT INTO StudentLogin VALUES (21, melwira, eaSBAFyk);
INSERT INTO StudentLogin VALUES (22, rfilia, ECRXwFLG);
INSERT INTO StudentLogin VALUES (23, jcarine, RjSpaoDx);
INSERT INTO StudentLogin VALUES (24, emmyewileen, kuDDPySj);
INSERT INTO Department VALUES (AFAM, Howarth);
INSERT INTO Department VALUES (ARTS, Kittredge);
INSERT INTO Department VALUES (ARTH, Wyatt);
INSERT INTO Department VALUES (BIOL, Thompson);
INSERT INTO Department VALUES (BUS, McIntyre);
INSERT INTO Department VALUES (CHEM, Thompson);
INSERT INTO Department VALUES (CSCI, Thompson);
INSERT INTO Department VALUES (ECON, McIntyre);
INSERT INTO Department VALUES (ENGL, Wyatt);
INSERT INTO Department VALUES (GEOL, Thompson);
INSERT INTO Department VALUES (HIST, Wyatt);
INSERT INTO Department VALUES (MATH, Thompson);
INSERT INTO Department VALUES (MUS, Music Building);
INSERT INTO Department VALUES (PG, Wyatt);
INSERT INTO Department VALUES (PHIL, Wyatt);
INSERT INTO Department VALUES (PHYS, Thompson);
INSERT INTO Department VALUES (PSYC, Weyerhaeuser);
INSERT INTO Department VALUES (SOAN, McIntyre);
INSERT INTO Major VALUES (0, CSCI);
INSERT INTO Major VALUES (1, CSCI);
INSERT INTO Major VALUES (2, CSCI);
INSERT INTO Major VALUES (3, CSCI);
INSERT INTO Major VALUES (4, CSCI);
INSERT INTO Major VALUES (5, CSCI);
INSERT INTO Major VALUES (6, CSCI);
INSERT INTO Major VALUES (7, CSCI);
INSERT INTO Major VALUES (9, CSCI);
INSERT INTO Major VALUES (10, CSCI);
INSERT INTO Major VALUES (12, CSCI);
INSERT INTO Major VALUES (13, CSCI);
INSERT INTO Major VALUES (15, CSCI);
INSERT INTO Major VALUES (16, CSCI);
INSERT INTO Major VALUES (17, CSCI);
INSERT INTO Major VALUES (18, CSCI);
INSERT INTO Major VALUES (19, CSCI);
INSERT INTO Major VALUES (21, CSCI);
INSERT INTO Major VALUES (22, CSCI);
INSERT INTO Major VALUES (23, CSCI);
INSERT INTO Major VALUES (24, CSCI);
INSERT INTO Minor VALUES (3, ARTS);
INSERT INTO Minor VALUES (4, HIST);
INSERT INTO Minor VALUES (5, BIOL);
INSERT INTO Minor VALUES (16, ECON);
INSERT INTO Minor VALUES (18, ENGL);
INSERT INTO Minor VALUES (19, MATH);
INSERT INTO Minor VALUES (21, PG);
INSERT INTO Minor VALUES (23, AFAM);
INSERT INTO Minor VALUES (24, PSYC);
INSERT INTO Professor VALUES (0, Zahara Andi, CSCI);
INSERT INTO Professor VALUES (1, Marin Georgine, CSCI);
INSERT INTO Professor VALUES (2, Jemmy Audry, CSCI);
INSERT INTO Professor VALUES (3, Brenda Simona, CSCI);
INSERT INTO Professor VALUES (4, Ealasaid Mireille, CSCI);
INSERT INTO Professor VALUES (5, Peggie Zonnya, CSCI);
INSERT INTO DepartmentHeads VALUES (CSCI, 0);
INSERT INTO ProfessorLogin VALUES (0, zandi, FoNmEpkE);
INSERT INTO ProfessorLogin VALUES (1, mgeorgine, LAFHZQFN);
INSERT INTO ProfessorLogin VALUES (2, jaudry, JaCAWweJ);
INSERT INTO ProfessorLogin VALUES (3, bsimona, cZnAqPVe);
INSERT INTO ProfessorLogin VALUES (4, emirielle, aQUhPYyj);
INSERT INTO ProfessorLogin VALUES (5, pzonnya, wkaBdfhv);
INSERT INTO Course VALUES (0, CSCI, 101 Introduction to Computer Science, 1, 1);
INSERT INTO Course VALUES (1, CSCI, 240 Software Engineering, 1, 1);
INSERT INTO Course VALUES (2, CSCI, 261 Computer Science II, 1, 1);
INSERT INTO Course VALUES (3, CSCI, 281 Assembly Language and Computer Architecture, 1, 1);
INSERT INTO Course VALUES (4, CSCI, 291 Programming Language Paradigms, 1, 1);
INSERT INTO Course VALUES (5, CSCI, 361 Algorithms and Data Structures, 1, 1);
INSERT INTO Course VALUES (6, CSCI, 440 Capstone in Computer Science, 0, 1);
INSERT INTO Enroll VALUES (0, 5);
INSERT INTO Enroll VALUES (1, 1);
INSERT INTO Enroll VALUES (1, 2);
INSERT INTO Enroll VALUES (2, 2);
INSERT INTO Enroll VALUES (2, 3);
INSERT INTO Enroll VALUES (3, 0);
INSERT INTO Enroll VALUES (4, 6);
INSERT INTO Enroll VALUES (5, 4);
INSERT INTO Enroll VALUES (6, 6);
INSERT INTO Enroll VALUES (7, 6);
INSERT INTO Enroll VALUES (8, 0);
INSERT INTO Enroll VALUES (9, 5);
INSERT INTO Enroll VALUES (9, 1);
INSERT INTO Enroll VALUES (10, 0);
INSERT INTO Enroll VALUES (11, 0);
INSERT INTO Enroll VALUES (12, 5);
INSERT INTO Enroll VALUES (13, 0);
INSERT INTO Enroll VALUES (14, 0);
INSERT INTO Enroll VALUES (15, 5);
INSERT INTO Enroll VALUES (16, 3);
INSERT INTO Enroll VALUES (16, 4);
INSERT INTO Enroll VALUES (17, 5);
INSERT INTO Enroll VALUES (18, 2);
INSERT INTO Enroll VALUES (19, 6);
INSERT INTO Enroll VALUES (20, 2);
INSERT INTO Enroll VALUES (21, 2);
INSERT INTO Enroll VALUES (21, 3);
INSERT INTO Enroll VALUES (22, 6);
INSERT INTO Enroll VALUES (23, 5);
INSERT INTO Enroll VALUES (24, 6);
INSERT INTO isMeeting VALUES (0, 0, A, Monday, 09:00, Thompson 409);
INSERT INTO isMeeting VALUES (0, 0, A, Wednesday, 09:00, Thompson 409);
INSERT INTO isMeeting VALUES (0, 0, A, Friday, 09:00, Thompson 409);
INSERT INTO isMeeting VALUES (0, 5, B, Monday, 11:00, Thompson 409);
INSERT INTO isMeeting VALUES (0, 5, B, Wednesday, 11:00, Thompson 409);
INSERT INTO isMeeting VALUES (0, 5, B, Friday, 11:00, Thompson 409);
INSERT INTO isMeeting VALUES (1, 2, A, Monday, 10:00, Thompson 399);
INSERT INTO isMeeting VALUES (1, 2, A, Wednesday, 10:00, Thompson 399);
INSERT INTO isMeeting VALUES (1, 2, A, Friday, 10:00, Thompson 399);
INSERT INTO isMeeting VALUES (2, 4, A, Monday, 13:00, Thompson 409);
INSERT INTO isMeeting VALUES (2, 4, A, Wednesday, 13:00, Thompson 409);
INSERT INTO isMeeting VALUES (2, 4, A, Friday, 13:00, Thompson 409);
INSERT INTO isMeeting VALUES (3, 1, A, Monday, 15:00, Thompson 399);
INSERT INTO isMeeting VALUES (3, 1, A, Wednesday, 15:00, Thompson 399);
INSERT INTO isMeeting VALUES (3, 1, A, Friday, 15:00, Thompson 399);
INSERT INTO isMeeting VALUES (4, 3, A, Tuesday, 11:00, Thompson 399);
INSERT INTO isMeeting VALUES (4, 3, A, Thursday, 11:00, Thompson 399);
INSERT INTO isMeeting VALUES (5, 4, A, Tuesday, 12:00, Thompson 409);
INSERT INTO isMeeting VALUES (5, 4, A, Thursday, 12:00, Thompson 409);
INSERT INTO isMeeting VALUES (6, 0, A, Monday, 16:00, Thompson 399);
INSERT INTO isMeeting VALUES (6, 0, A, Friday, 16:00, Thompson 399);
INSERT INTO isRequired VALUES (1, 0);
INSERT INTO isRequired VALUES (2, 0);
INSERT INTO isRequired VALUES (3, 0);
INSERT INTO isRequired VALUES (4, 0);
INSERT INTO isRequired VALUES (5, 2);
INSERT INTO isRequired VALUES (5, 3);
INSERT INTO isRequired VALUES (5, 4);
INSERT INTO isRequired VALUES (6, 5);
INSERT INTO isRequired VALUES (6, 1);