INSERT INTO Students VALUES (0, 'Ame Anna-Diana', 'Junior', '1.6');
INSERT INTO Students VALUES (1, 'Eachelle Quintina', 'Sophomore', '1.9');
INSERT INTO Students VALUES (2, 'Cayla Dion', 'Sophomore', '2.0');       
INSERT INTO Students VALUES (3, 'Gayla Inez', 'Freshman', '3.4');        
INSERT INTO Students VALUES (4, 'Cathi Shae', 'Senior', '3.0');
INSERT INTO Students VALUES (5, 'Sonja Benita', 'Sophomore', '2.6');     
INSERT INTO Students VALUES (6, 'Bobbette Viola', 'Senior', '0.3');      
INSERT INTO Students VALUES (7, 'Vitia Tootsie', 'Senior', '3.8');       
INSERT INTO Students VALUES (8, 'Tansy Judy', 'Freshman', '0.7');        
INSERT INTO Students VALUES (9, 'Oralle Johanna', 'Junior', '3.4');
INSERT INTO Students VALUES (10, 'Kellia Martita', 'Freshman', '3.2');
INSERT INTO Students VALUES (11, 'Vida Cherrita', 'Freshman', '0.9');
INSERT INTO Students VALUES (12, 'Emmalynn Wylma', 'Junior', '1.9');
INSERT INTO Students VALUES (13, 'Joycelin Babita', 'Freshman', '3.5');
INSERT INTO Students VALUES (14, 'Amelina Krystyna', 'Freshman', '0.9');
INSERT INTO Students VALUES (15, 'Danice Mehetabel', 'Junior', '2.8');
INSERT INTO Students VALUES (16, 'Joella Anett', 'Sophomore', '3.5');
INSERT INTO Students VALUES (17, 'Chelsey Druci', 'Junior', '0.9');
INSERT INTO Students VALUES (18, 'Adina Marleah', 'Sophomore', '3.7');
INSERT INTO Students VALUES (19, 'Andriana Leslie', 'Senior', '1.4');
INSERT INTO Students VALUES (20, 'Gertrudis Phebe', 'Freshman', '1.4');
INSERT INTO Students VALUES (21, 'Malissa Elwira', 'Sophomore', '3.9');
INSERT INTO Students VALUES (22, 'Reina Filia', 'Senior', '4.0');
INSERT INTO Students VALUES (23, 'Jayne Carine', 'Junior', '3.9');
INSERT INTO Students VALUES (24, 'Emmye Wileen', 'Senior', '3.4');
INSERT INTO StudentLogin VALUES (0, 'aadiana', 'zSLPj4JV');
INSERT INTO StudentLogin VALUES (1, 'equintina', '2JxCQnub');
INSERT INTO StudentLogin VALUES (2, 'cdion', '4vmZmHA3');
INSERT INTO StudentLogin VALUES (3, 'ginez', '5tLyKNrQ');
INSERT INTO StudentLogin VALUES (4, 'cshae', '57T22Kic');
INSERT INTO StudentLogin VALUES (5, 'sbenita', 'xpjD8H25');
INSERT INTO StudentLogin VALUES (6, 'bviola', 'pECG4u90');
INSERT INTO StudentLogin VALUES (7, 'vtootsie', 'aL10lSN9');
INSERT INTO StudentLogin VALUES (8, 'tjudy', '7PCfvUaL');
INSERT INTO StudentLogin VALUES (9, 'ojohanna', 'Xfr5YYjw');
INSERT INTO StudentLogin VALUES (10, 'kmartita', 'lCMl8iqs');
INSERT INTO StudentLogin VALUES (11, 'vcherrita', 'WzU4RMrE');
INSERT INTO StudentLogin VALUES (12, 'ewylma', '9Ug3Aof3');
INSERT INTO StudentLogin VALUES (13, 'jbabita', 'UX1hwD0y');
INSERT INTO StudentLogin VALUES (14, 'akrystyna', 'mlNT9KUE');
INSERT INTO StudentLogin VALUES (15, 'dehetabel', '8O9ly2q0');
INSERT INTO StudentLogin VALUES (16, 'janett', '8yfe5WHs');
INSERT INTO StudentLogin VALUES (17, 'cdruci', '5lSjrHHm');
INSERT INTO StudentLogin VALUES (18, 'amarleah', 'NM1Rragv');
INSERT INTO StudentLogin VALUES (19, 'aleslie', 'z3VzxC1V');
INSERT INTO StudentLogin VALUES (20, 'gphebe', 'C473YzQz');
INSERT INTO StudentLogin VALUES (21, 'melwira', 'vX2is8wx');
INSERT INTO StudentLogin VALUES (22, 'rfilia', 'wT26iswF');
INSERT INTO StudentLogin VALUES (23, 'jcarine', 'aiY864fk');
INSERT INTO StudentLogin VALUES (24, 'ewileen', 'Cmnoc0O1');
INSERT INTO Department VALUES ('AFAM', 'African American Studies', 'Howarth');
INSERT INTO Department VALUES ('ARTS', 'Studio Art', 'Kittredge');
INSERT INTO Department VALUES ('ARTH', 'Art History', 'Wyatt');
INSERT INTO Department VALUES ('BIOL', 'Biology', 'Thompson');
INSERT INTO Department VALUES ('BUS', 'Business', 'McIntyre');
INSERT INTO Department VALUES ('CHEM', 'Chemistry', 'Thompson');
INSERT INTO Department VALUES ('CSCI', 'Computer Science', 'Thompson');
INSERT INTO Department VALUES ('ECON', 'Economics', 'McIntyre');
INSERT INTO Department VALUES ('ENGL', 'English', 'Wyatt');
INSERT INTO Department VALUES ('GEOL', 'Geology', 'Thompson');
INSERT INTO Department VALUES ('HIST', 'History', 'Wyatt');
INSERT INTO Department VALUES ('MATH', 'Math', 'Thompson');
INSERT INTO Department VALUES ('MUS', 'Music', 'Music Building');
INSERT INTO Department VALUES ('PG', 'Politics and Government', 'Wyatt');
INSERT INTO Department VALUES ('PHIL', 'Philosophy', 'Wyatt');
INSERT INTO Department VALUES ('PHYS', 'Physics', 'Thompson');
INSERT INTO Department VALUES ('PSYC', 'Psychology', 'Weyerhaeuser');
INSERT INTO Department VALUES ('SOAN', 'Sociology and Antropology', 'McIntyre');
INSERT INTO Major VALUES (0, 'CSCI');
INSERT INTO Major VALUES (2, 'CSCI');
INSERT INTO Major VALUES (3, 'CSCI');
INSERT INTO Major VALUES (4, 'CSCI');
INSERT INTO Major VALUES (5, 'CSCI');
INSERT INTO Major VALUES (6, 'CSCI');
INSERT INTO Major VALUES (7, 'CSCI');
INSERT INTO Major VALUES (9, 'CSCI');
INSERT INTO Major VALUES (10, 'CSCI');
INSERT INTO Major VALUES (12, 'CSCI');
INSERT INTO Major VALUES (13, 'CSCI');
INSERT INTO Major VALUES (15, 'CSCI');
INSERT INTO Major VALUES (16, 'CSCI');
INSERT INTO Major VALUES (17, 'CSCI');
INSERT INTO Major VALUES (18, 'CSCI');
INSERT INTO Major VALUES (19, 'CSCI');
INSERT INTO Major VALUES (21, 'CSCI');
INSERT INTO Major VALUES (22, 'CSCI');
INSERT INTO Major VALUES (23, 'CSCI');
INSERT INTO Major VALUES (24, 'CSCI');
INSERT INTO Minor VALUES (3, 'ARTS');
INSERT INTO Minor VALUES (5, 'PHIL');
INSERT INTO Minor VALUES (13, 'MUS');
INSERT INTO Minor VALUES (16, 'BUS');
INSERT INTO Minor VALUES (18, 'PSYC');
INSERT INTO Minor VALUES (22, 'CHEM');
INSERT INTO Minor VALUES (23, 'AFAM');
INSERT INTO Professor VALUES (0, 'Goldia Daisi', 'CSCI');
INSERT INTO Professor VALUES (1, 'Junette Vernice', 'CSCI');
INSERT INTO Professor VALUES (2, 'Korie Danella', 'CSCI');
INSERT INTO Professor VALUES (3, 'Liz Viv', 'CSCI');
INSERT INTO Professor VALUES (4, 'Marlie Nannette', 'CSCI');
INSERT INTO Professor VALUES (5, 'Johna Pierette', 'CSCI');
INSERT INTO DepartmentHeads VALUES ('CSCI', 3);
INSERT INTO ProfessorLogin VALUES (0, 'gdaisi', 'dc4I}+sDY');
INSERT INTO ProfessorLogin VALUES (1, 'jvernice', '7N~.}MgKfX');
INSERT INTO ProfessorLogin VALUES (2, 'kdanella', 'm0]!lFjvpp');
INSERT INTO ProfessorLogin VALUES (3, 'lviv', 'GM4;mP]Zz?');
INSERT INTO ProfessorLogin VALUES (4, 'mnannette', 'j>~`N0m4Ga');
INSERT INTO ProfessorLogin VALUES (5, 'jpierette', 'v(`Qosw4]p');
INSERT INTO Course VALUES (0, 'CSCI', '101 Introduction to Computer Science', 1, 1);
INSERT INTO Course VALUES (1, 'CSCI', '240 Software Engineering', 1, 1);
INSERT INTO Course VALUES (2, 'CSCI', '261 Computer Science II', 1, 1);
INSERT INTO Course VALUES (3, 'CSCI', '281 Assembly Language and Computer Architecture', 1, 1);
INSERT INTO Course VALUES (4, 'CSCI', '291 Programming Language Paradigms', 1, 1);
INSERT INTO Course VALUES (5, 'CSCI', '361 Algorithms and Data Structures', 1, 1);
INSERT INTO Course VALUES (6, 'CSCI', '440 Capstone in Computer Science', 0, 1);
INSERT INTO Enroll VALUES (0, 5);
INSERT INTO Enroll VALUES (1, 1);
INSERT INTO Enroll VALUES (1, 2);
INSERT INTO Enroll VALUES (2, 2);
INSERT INTO Enroll VALUES (2, 3);
INSERT INTO Enroll VALUES (3, 0);
INSERT INTO Enroll VALUES (4, 6);
INSERT INTO Enroll VALUES (5, 4);
INSERT INTO Enroll VALUES (6, 6);
INSERT INTO Enroll VALUES (7, 6);
INSERT INTO Enroll VALUES (8, 0);
INSERT INTO Enroll VALUES (9, 5);
INSERT INTO Enroll VALUES (9, 1);
INSERT INTO Enroll VALUES (10, 0);
INSERT INTO Enroll VALUES (11, 0);
INSERT INTO Enroll VALUES (12, 5);
INSERT INTO Enroll VALUES (13, 0);
INSERT INTO Enroll VALUES (14, 0);
INSERT INTO Enroll VALUES (15, 5);
INSERT INTO Enroll VALUES (16, 3);
INSERT INTO Enroll VALUES (16, 4);
INSERT INTO Enroll VALUES (17, 5);
INSERT INTO Enroll VALUES (18, 2);
INSERT INTO Enroll VALUES (19, 6);
INSERT INTO Enroll VALUES (20, 2);
INSERT INTO Enroll VALUES (21, 2);
INSERT INTO Enroll VALUES (21, 3);
INSERT INTO Enroll VALUES (22, 6);
INSERT INTO Enroll VALUES (23, 5);
INSERT INTO Enroll VALUES (24, 6);
INSERT INTO Teaching VALUES (0, 'A', 3);
INSERT INTO Teaching VALUES (0, 'B', 0);
INSERT INTO Teaching VALUES (1, 'A', 3);
INSERT INTO Teaching VALUES (2, 'A', 4);
INSERT INTO Teaching VALUES (2, 'B', 0);
INSERT INTO Teaching VALUES (3, 'A', 2);
INSERT INTO Teaching VALUES (4, 'A', 5);
INSERT INTO Teaching VALUES (5, 'A', 1);
INSERT INTO Teaching VALUES (6, 'A', 3);
INSERT INTO IsMeeting VALUES (0, 'A', 'Monday', '09:00', '09:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (0, 'A', 'Wednesday', '09:00', '09:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (0, 'A', 'Friday', '09:00', '09:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (0, 'B', 'Tuesday', '09:00', '09:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (0, 'B', 'Thursday', '09:00', '09:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (1, 'A', 'Tuesday', '10:00', '10:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (1, 'A', 'Thursday', '10:00', '10:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (2, 'A', 'Monday', '10:00', '10:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (2, 'A', 'Wednesday', '10:00', '10:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (2, 'A', 'Friday', '10:00', '10:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (2, 'B', 'Tuesday', '12:00', '13:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (2, 'B', 'Thursday', '12:00', '13:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (3, 'A', 'Monday', '12:00', '12:50', 'Thompson 301');
INSERT INTO IsMeeting VALUES (3, 'A', 'Wednesday', '12:00', '12:50', 'Thompson 301');
INSERT INTO IsMeeting VALUES (3, 'A', 'Friday', '12:00', '12:50', 'Thompson 301');
INSERT INTO IsMeeting VALUES (4, 'A', 'Monday', '11:00', '11:50', 'Thompson 356');
INSERT INTO IsMeeting VALUES (4, 'A', 'Wednesday', '11:00', '11:50', 'Thompson 356');
INSERT INTO IsMeeting VALUES (4, 'A', 'Friday', '11:00', '11:50', 'Thompson 356');
INSERT INTO IsMeeting VALUES (5, 'A', 'Monday', '13:00', '13:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (5, 'A', 'Wednesday', '13:00', '13:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (5, 'A', 'Friday', '13:00', '13:50', 'Thompson 409');
INSERT INTO IsMeeting VALUES (6, 'A', 'Monday', '15:00', '15:50', 'Thompson 356');
INSERT INTO IsMeeting VALUES (6, 'A', 'Friday', '15:00', '15:50', 'Thompson 356');
INSERT INTO Requirements VALUES (1, 0);
INSERT INTO Requirements VALUES (2, 0);
INSERT INTO Requirements VALUES (3, 0);
INSERT INTO Requirements VALUES (4, 0);
INSERT INTO Requirements VALUES (5, 2);
INSERT INTO Requirements VALUES (5, 3);
INSERT INTO Requirements VALUES (5, 4);
INSERT INTO Requirements VALUES (6, 1);
INSERT INTO Requirements VALUES (6, 5);
INSERT INTO ClassRequirements VALUES (6, 'Senior');
